/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Produtos;
import dao.ProdutosDAO;
import tools.Util;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
/**
 *
 * @author u10916731103
 */
public class JDlgProdutos extends javax.swing.JDialog {

    private boolean incluir;
        
    public JDlgProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Usuários");
        setLocationRelativeTo(null);
        Util.habilitar(false, jTxtPeso, jTxtNome, jBtnCancelar, jBtnConfirmar, jBtnAlterar, jBtnExcluir,
                jCboNivel,
                jChbAtivo, jFmtPreco, jFmtPeso, jTxtDescricao);
        TitledBorder Preco = BorderFactory.createTitledBorder("Preço");
        TitledBorder DataNasc = BorderFactory.createTitledBorder("Data de Nascimento");
        jFmtPreco.setBorder(Preco);
        jFmtPeso.setBorder(DataNasc);

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtPeso = new javax.swing.JTextField();
        jTxtNome = new javax.swing.JTextField();
        jTxtDescricao = new javax.swing.JTextField();
        jFmtPreco = new javax.swing.JFormattedTextField();
        jFmtPeso = new javax.swing.JFormattedTextField();
        jChbAtivo = new javax.swing.JCheckBox();
        jCboNivel = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jTxtCodigo1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTxtPeso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxtPeso.setBorder(javax.swing.BorderFactory.createTitledBorder("Peso"));
        jTxtPeso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtPesoFocusLost(evt);
            }
        });
        jTxtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPesoActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 180, 46));

        jTxtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxtNome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 78, 451, 50));

        jTxtDescricao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxtDescricao.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));
        getContentPane().add(jTxtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 137, 451, 200));

        jFmtPreco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFmtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtPrecoActionPerformed(evt);
            }
        });
        getContentPane().add(jFmtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 169, 48));
        getContentPane().add(jFmtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 216, 50));
        getContentPane().add(jChbAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 437, -1, -1));

        jCboNivel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jCboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5%", "10%", "15%", "20%", "25%", "30%", "35%", "40%", "45%", "50%", "55%", "60%", "65%", "70%", "75%", "80%", "85%", "90%", "95%", "100%", " " }));
        jCboNivel.setBorder(javax.swing.BorderFactory.createTitledBorder("% Cacau"));
        jCboNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboNivelActionPerformed(evt);
            }
        });
        getContentPane().add(jCboNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 423, 151, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Ativo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 437, -1, 21));

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/img/icons8-adicionar-50.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 510, -1, -1));

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/img/icons8-alterar-50.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 510, -1, -1));

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/img/icons8-lixo-50.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 512, -1, -1));

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/img/icons8-confirmar-50.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 587, -1, -1));

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/img/icons8-cancelar-50.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 587, -1, -1));

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/img/icons8-pesquisar-50.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 587, -1, -1));

        jTxtCodigo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxtCodigo1.setBorder(javax.swing.BorderFactory.createTitledBorder("Código"));
        jTxtCodigo1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtCodigo1FocusLost(evt);
            }
        });
        jTxtCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 16, 133, 46));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxtPeso, jTxtNome, jBtnCancelar, jBtnConfirmar,
                jCboNivel, jChbAtivo, jFmtPreco, jFmtPeso,  jTxtDescricao);
        Util.habilitar(false, jBtnAlterar, jBtnExcluir, jBtnIncluir, jBtnPesquisar);
        Util.limpar(jTxtPeso,jCboNivel, jChbAtivo, jTxtNome,jFmtPreco, jFmtPeso,  jTxtDescricao);
        jTxtCodigo1.grabFocus();
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxtPeso, jTxtNome, jBtnCancelar, jBtnConfirmar,
                jCboNivel, jChbAtivo, jFmtPreco, jFmtPeso,  jTxtDescricao);
        Util.habilitar(false, jBtnAlterar, jBtnExcluir, jBtnIncluir, jBtnPesquisar);
        

    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (Util.perguntar("DEseja apacar") == true) {
            
        }
    }//GEN-LAST:event_jBtnExcluirActionPerformed


    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        ProdutosDAO usuariosDAO = new ProdutosDAO();
        if (incluir == false) {
          //  ProdutosDAO.insert(viewBean());
        }// else usuariosDAO.update(viewBean());
        
        Util.habilitar(false, jTxtPeso, jTxtNome, jBtnCancelar, jBtnConfirmar,
                jCboNivel, jChbAtivo, jFmtPreco, jFmtPeso,  jTxtDescricao);
        Util.habilitar(true, jBtnAlterar, jBtnExcluir, jBtnIncluir, jBtnPesquisar);
       

    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here: 


    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtPeso, jTxtNome, jBtnCancelar, jBtnConfirmar,
                jCboNivel, jChbAtivo, jFmtPreco, jFmtPeso,  jTxtDescricao);
        Util.habilitar(true, jBtnAlterar, jBtnExcluir, jBtnIncluir, jBtnPesquisar);
             Util.limpar(jTxtPeso,jCboNivel, jChbAtivo, jTxtNome,jFmtPreco, jFmtPeso,  jTxtDescricao);
    

    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTxtPesoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtPesoFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jTxtPesoFocusLost

    private void jCboNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboNivelActionPerformed

    private void jTxtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPesoActionPerformed

    private void jFmtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtPrecoActionPerformed

    private void jTxtCodigo1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCodigo1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigo1FocusLost

    private void jTxtCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgProdutos dialog = new JDlgProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<String> jCboNivel;
    private javax.swing.JCheckBox jChbAtivo;
    private javax.swing.JFormattedTextField jFmtPeso;
    private javax.swing.JFormattedTextField jFmtPreco;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTxtCodigo1;
    private javax.swing.JTextField jTxtDescricao;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtPeso;
    // End of variables declaration//GEN-END:variables
}
