package bean;
// Generated 15/09/2025 07:57:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name="clientes"
    ,catalog="db_marcos_vilhanueva"
)
public class Clientes  implements java.io.Serializable {


     private int idclientes;
     private String nome;
     private String cpf;
     private String rg;
     private String cep;
     private String endereco;
     private String numero;
     private String bairro;
     private Integer estadocivil;
     private Integer sexo;
     private Set pedidoses = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(int idclientes) {
        this.idclientes = idclientes;
    }
    public Clientes(int idclientes, String nome, String cpf, String rg, String cep, String endereco, String numero, String bairro, Integer estadocivil, Integer sexo, Set pedidoses) {
       this.idclientes = idclientes;
       this.nome = nome;
       this.cpf = cpf;
       this.rg = rg;
       this.cep = cep;
       this.endereco = endereco;
       this.numero = numero;
       this.bairro = bairro;
       this.estadocivil = estadocivil;
       this.sexo = sexo;
       this.pedidoses = pedidoses;
    }
   
     @Id 

    
    @Column(name="idclientes", unique=true, nullable=false)
    public int getIdclientes() {
        return this.idclientes;
    }
    
    public void setIdclientes(int idclientes) {
        this.idclientes = idclientes;
    }

    
    @Column(name="nome", length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="cpf", length=15)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="rg", length=15)
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }

    
    @Column(name="cep", length=10)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="endereco", length=50)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="numero", length=5)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="bairro", length=45)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="estadocivil")
    public Integer getEstadocivil() {
        return this.estadocivil;
    }
    
    public void setEstadocivil(Integer estadocivil) {
        this.estadocivil = estadocivil;
    }

    
    @Column(name="sexo")
    public Integer getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Integer sexo) {
        this.sexo = sexo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clientes")
    public Set getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set pedidoses) {
        this.pedidoses = pedidoses;
    }




}


