package bean;
// Generated 13/10/2025 05:11:39 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name="clientes"
    ,catalog="db_vinicius_nunes"
)
public class Clientes  implements java.io.Serializable {


     private int idclientes;
     private String bairro;
     private String cep;
     private String cpf;
     private String endereco;
     private int estadocivil;
     private String nome;
     private String numero;
     private String rg;
     private int sexo;

    public Clientes() {
    }

	
    public Clientes(int idclientes) {
        this.idclientes = idclientes;
    }
    public Clientes(int idclientes, String bairro, String cep, String cpf, String endereco, int estadocivil, String nome, String numero, String rg, int sexo) {
       this.idclientes = idclientes;
       this.bairro = bairro;
       this.cep = cep;
       this.cpf = cpf;
       this.endereco = endereco;
       this.estadocivil = estadocivil;
       this.nome = nome;
       this.numero = numero;
       this.rg = rg;
       this.sexo = sexo;
    }
   
     @Id 

    
    @Column(name="idclientes", unique=true, nullable=false)
    public int getIdclientes() {
        return this.idclientes;
    }
    
    public void setIdclientes(int idclientes) {
        this.idclientes = idclientes;
    }

    
    @Column(name="bairro", length=45)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="cep", length=10)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="cpf", length=15)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="endereco", length=50)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="estadocivil")
    public int getEstadocivil() {
        return this.estadocivil;
    }
    
    public void setEstadocivil(int estadocivil) {
        this.estadocivil = estadocivil;
    }

    
    @Column(name="nome", length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="numero", length=5)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="rg", length=15)
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }

    
    @Column(name="sexo")
    public int getSexo() {
        return this.sexo;
    }
    
    public void setSexo(int sexo) {
        this.sexo = sexo;
    }




}


