package bean;
// Generated 13/10/2025 05:11:39 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedidos generated by hbm2java
 */
@Entity
@Table(name="pedidos"
    ,catalog="db_vinicius_nunes"
)
public class Pedidos  implements java.io.Serializable {


     private int idpedidos;
     private Clientes clientes;
     private Date data;
     private double total;
     private Vendedor vendedor;

    public Pedidos() {
    }

	
    public Pedidos(int idpedidos) {
        this.idpedidos = idpedidos;
    }
    public Pedidos(int idpedidos, Clientes clientes, Date data, double total, Vendedor vendedor) {
       this.idpedidos = idpedidos;
       this.clientes = clientes;
       this.data = data;
       this.total = total;
       this.vendedor = vendedor;
    }
   
     @Id 

    
    @Column(name="idpedidos", unique=true, nullable=false)
    public int getIdpedidos() {
        return this.idpedidos;
    }
    
    public void setIdpedidos(int idpedidos) {
        this.idpedidos = idpedidos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente")
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data", length=10)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    
    @Column(name="total", precision=10, scale=0)
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vendedor")
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }




}


