package bean;
// Generated 15/09/2025 07:57:35 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedidos generated by hbm2java
 */
@Entity
@Table(name="pedidos"
    ,catalog="db_marcos_vilhanueva"
)
public class Pedidos  implements java.io.Serializable {


     private int idpedidos;
     private Clientes clientes;
     private Vendedor vendedor;
     private Date data;
     private BigDecimal total;
     private Set pedidosProdutoses = new HashSet(0);

    public Pedidos() {
    }

	
    public Pedidos(int idpedidos) {
        this.idpedidos = idpedidos;
    }
    public Pedidos(int idpedidos, Clientes clientes, Vendedor vendedor, Date data, BigDecimal total, Set pedidosProdutoses) {
       this.idpedidos = idpedidos;
       this.clientes = clientes;
       this.vendedor = vendedor;
       this.data = data;
       this.total = total;
       this.pedidosProdutoses = pedidosProdutoses;
    }
   
     @Id 

    
    @Column(name="idpedidos", unique=true, nullable=false)
    public int getIdpedidos() {
        return this.idpedidos;
    }
    
    public void setIdpedidos(int idpedidos) {
        this.idpedidos = idpedidos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente")
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vendedor")
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data", length=10)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    
    @Column(name="total", precision=10)
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pedidos")
    public Set getPedidosProdutoses() {
        return this.pedidosProdutoses;
    }
    
    public void setPedidosProdutoses(Set pedidosProdutoses) {
        this.pedidosProdutoses = pedidosProdutoses;
    }




}


