package bean;
// Generated 13/10/2025 05:11:39 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PedidosProdutos generated by hbm2java
 */
@Entity
@Table(name="pedidos_produtos"
    ,catalog="db_vinicius_nunes"
)
public class PedidosProdutos  implements java.io.Serializable {


     private int idpedidosProdutos;
     private Pedidos pedidos;
     private Produtos produtos;
     private int quantidade;
     private double valorUnitario;

    public PedidosProdutos() {
    }

    public PedidosProdutos(Pedidos pedidos, Produtos produtos, int quantidade, double valorUnitario) {
       this.pedidos = pedidos;
       this.produtos = produtos;
       this.quantidade = quantidade;
       this.valorUnitario = valorUnitario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idpedidos_produtos", unique=true, nullable=false)
    public int getIdpedidosProdutos() {
        return this.idpedidosProdutos;
    }
    
    public void setIdpedidosProdutos(int idpedidosProdutos) {
        this.idpedidosProdutos = idpedidosProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pedidos")
    public Pedidos getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Pedidos pedidos) {
        this.pedidos = pedidos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produtos")
    public Produtos getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Produtos produtos) {
        this.produtos = produtos;
    }

    
    @Column(name="quantidade")
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="valorUnitario", precision=10, scale=0)
    public double getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(double valorUnitario) {
        this.valorUnitario = valorUnitario;
    }




}


