package bean;
// Generated 13/10/2025 05:11:39 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Produtos generated by hbm2java
 */
@Entity
@Table(name="produtos"
    ,catalog="db_vinicius_nunes"
)
public class Produtos  implements java.io.Serializable {


     private int idprodutos;
     private int grupo;
     private String nome;
     private double valorUnitario;

    public Produtos() {
    }

	
    public Produtos(int idprodutos) {
        this.idprodutos = idprodutos;
    }
    public Produtos(int idprodutos, int grupo, String nome, double valorUnitario) {
       this.idprodutos = idprodutos;
       this.grupo = grupo;
       this.nome = nome;
       this.valorUnitario = valorUnitario;
    }
   
     @Id 

    
    @Column(name="idprodutos", unique=true, nullable=false)
    public int getIdprodutos() {
        return this.idprodutos;
    }
    
    public void setIdprodutos(int idprodutos) {
        this.idprodutos = idprodutos;
    }

    
    @Column(name="grupo")
    public int getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(int grupo) {
        this.grupo = grupo;
    }

    
    @Column(name="nome", length=60)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="valorUnitario", precision=10, scale=0)
    public double getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(double valorUnitario) {
        this.valorUnitario = valorUnitario;
    }




}


