package bean;
// Generated 13/10/2025 05:11:39 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="vman_usuarios"
    ,catalog="db_vinicius_nunes"
)
public class Usuarios  implements java.io.Serializable {


     private int idusuarios;
     private String apelido;
     private String ativo;
     private String cpf;
     private Date dataNascimento;
     private int nivel;
     private String nome;
     private String senha;

    public Usuarios() {
    }

	
  
    public Usuarios(int idusuarios, String apelido, String ativo, String cpf, Date dataNascimento, int nivel, String nome, String senha) {
       this.idusuarios = idusuarios;
       this.apelido = apelido;
       this.ativo = ativo;
       this.cpf = cpf;
       this.dataNascimento = dataNascimento;
       this.nivel = nivel;
       this.nome = nome;
       this.senha = senha;
    }
   
     @Id 

    
    @Column(name="vman_idusuarios", unique=true, nullable=false)
    public int getIdusuarios() {
        return this.idusuarios;
    }
    
    public void setIdusuarios(int idusuarios) {
        this.idusuarios = idusuarios;
    }

    
    @Column(name="vman_apelido", nullable=false, length=45)
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }

    
    @Column(name="vman_ativo", nullable=false, length=1)
    public String getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(String ativo) {
        this.ativo = ativo;
    }

    
    @Column(name="vman_cpf", length=15)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="vman_dataNascimento", length=10)
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    
    @Column(name="vman_nivel", nullable=false)
    public int getNivel() {
        return this.nivel;
    }
    
    public void setNivel(int nivel) {
        this.nivel = nivel;
    }

    
    @Column(name="vman_nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="vman_senha", nullable=false, length=15)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


