package bean;
// Generated 13/10/2025 05:11:39 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vendedor generated by hbm2java
 */
@Entity
@Table(name="vendedor"
    ,catalog="db_vinicius_nunes"
)
public class Vendedor  implements java.io.Serializable {


     private int idvendedor;
     private double comissao;
     private String nome;
     private double salario;
     private String vendedorcol;

    public Vendedor() {
    }

	
    public Vendedor(int idvendedor) {
        this.idvendedor = idvendedor;
    }
    public Vendedor(int idvendedor, double comissao, String nome, double salario, String vendedorcol) {
       this.idvendedor = idvendedor;
       this.comissao = comissao;
       this.nome = nome;
       this.salario = salario;
       this.vendedorcol = vendedorcol;
    }
   
     @Id 

    
    @Column(name="idvendedor", unique=true, nullable=false)
    public int getIdvendedor() {
        return this.idvendedor;
    }
    
    public void setIdvendedor(int idvendedor) {
        this.idvendedor = idvendedor;
    }

    
    @Column(name="comissao", precision=10, scale=0)
    public double getComissao() {
        return this.comissao;
    }
    
    public void setComissao(double comissao) {
        this.comissao = comissao;
    }

    
    @Column(name="nome", length=60)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="salario", precision=10, scale=0)
    public double getSalario() {
        return this.salario;
    }
    
    public void setSalario(double salario) {
        this.salario = salario;
    }

    
    @Column(name="vendedorcol", length=45)
    public String getVendedorcol() {
        return this.vendedorcol;
    }
    
    public void setVendedorcol(String vendedorcol) {
        this.vendedorcol = vendedorcol;
    }




}


