package bean;
// Generated 13/10/2025 14:53:13 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VmanVendas generated by hbm2java
 */
@Entity
@Table(name="vman_vendas"
    ,catalog="db_vinicius_nunes"
)
public class VmanVendas  implements java.io.Serializable {


     private int vmanIdVendas;
     private VmanClientes vmanClientes;
     private VmanVendedor vmanVendedor;
     private Date vmanDataVendas;
     private double vmanTotal;
 

    public VmanVendas() {
    }

	
    public VmanVendas(int vmanIdVendas) {
        this.vmanIdVendas = vmanIdVendas;
    }
    public VmanVendas(int vmanIdVendas, VmanClientes vmanClientes, VmanVendedor vmanVendedor, Date vmanDataVendas, double vmanTotal, Set vmanVendasProdutoses) {
       this.vmanIdVendas = vmanIdVendas;
       this.vmanClientes = vmanClientes;
       this.vmanVendedor = vmanVendedor;
       this.vmanDataVendas = vmanDataVendas;
       this.vmanTotal = vmanTotal;
     
    }
   
     @Id 

    
    @Column(name="vman_idVendas", unique=true, nullable=false)
    public int getVmanIdVendas() {
        return this.vmanIdVendas;
    }
    
    public void setVmanIdVendas(int vmanIdVendas) {
        this.vmanIdVendas = vmanIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vman_cliente")
    public VmanClientes getVmanClientes() {
        return this.vmanClientes;
    }
    
    public void setVmanClientes(VmanClientes vmanClientes) {
        this.vmanClientes = vmanClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vman_usuario")
    public VmanVendedor getVmanVendedor() {
        return this.vmanVendedor;
    }
    
    public void setVmanVendedor(VmanVendedor vmanVendedor) {
        this.vmanVendedor = vmanVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="vman_dataVendas", length=10)
    public Date getVmanDataVendas() {
        return this.vmanDataVendas;
    }
    
    public void setVmanDataVendas(Date vmanDataVendas) {
        this.vmanDataVendas = vmanDataVendas;
    }

    
    @Column(name="vman_total", precision=10)
    public double getVmanTotal() {
        return this.vmanTotal;
    }
    
    public void setVmanTotal(double vmanTotal) {
        this.vmanTotal = vmanTotal;
    }






}


