package bean;
// Generated 13/10/2025 14:53:13 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VmanUsuarios generated by hbm2java
 */
@Entity
@Table(name="vman_usuarios"
    ,catalog="db_vinicius_nunes"
)
public class VmanUsuarios  implements java.io.Serializable {


     private int vmanIdusuarios;
     private String vmanNome;
     private String vmanApelido;
     private String vmanCpf;
     private Date vmanDataNascimento;
     private String vmanSenha;
     private int vmanNivel;
     private String vmanAtivo;

    public VmanUsuarios() {
    }

	
    public VmanUsuarios(int vmanIdusuarios) {
        this.vmanIdusuarios = vmanIdusuarios;
    }
    public VmanUsuarios(int vmanIdusuarios, String vmanNome, String vmanApelido, String vmanCpf, Date vmanDataNascimento, String vmanSenha, int vmanNivel, String vmanAtivo) {
       this.vmanIdusuarios = vmanIdusuarios;
       this.vmanNome = vmanNome;
       this.vmanApelido = vmanApelido;
       this.vmanCpf = vmanCpf;
       this.vmanDataNascimento = vmanDataNascimento;
       this.vmanSenha = vmanSenha;
       this.vmanNivel = vmanNivel;
       this.vmanAtivo = vmanAtivo;
    }
   
     @Id 

    
    @Column(name="vman_idusuarios", unique=true, nullable=false)
    public int getVmanIdusuarios() {
        return this.vmanIdusuarios;
    }
    
    public void setVmanIdusuarios(int vmanIdusuarios) {
        this.vmanIdusuarios = vmanIdusuarios;
    }

    
    @Column(name="vman_nome", length=50)
    public String getVmanNome() {
        return this.vmanNome;
    }
    
    public void setVmanNome(String vmanNome) {
        this.vmanNome = vmanNome;
    }

    
    @Column(name="vman_apelido", length=45)
    public String getVmanApelido() {
        return this.vmanApelido;
    }
    
    public void setVmanApelido(String vmanApelido) {
        this.vmanApelido = vmanApelido;
    }

    
    @Column(name="vman_cpf", length=14)
    public String getVmanCpf() {
        return this.vmanCpf;
    }
    
    public void setVmanCpf(String vmanCpf) {
        this.vmanCpf = vmanCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="vman_dataNascimento", length=10)
    public Date getVmanDataNascimento() {
        return this.vmanDataNascimento;
    }
    
    public void setVmanDataNascimento(Date vmanDataNascimento) {
        this.vmanDataNascimento = vmanDataNascimento;
    }

    
    @Column(name="vman_senha", length=30)
    public String getVmanSenha() {
        return this.vmanSenha;
    }
    
    public void setVmanSenha(String vmanSenha) {
        this.vmanSenha = vmanSenha;
    }

    
    @Column(name="vman_nivel")
    public int getVmanNivel() {
        return this.vmanNivel;
    }
    
    public void setVmanNivel(int vmanNivel) {
        this.vmanNivel = vmanNivel;
    }

    
    @Column(name="vman_ativo", length=1)
    public String getVmanAtivo() {
        return this.vmanAtivo;
    }
    
    public void setVmanAtivo(String vmanAtivo) {
        this.vmanAtivo = vmanAtivo;
    }




}


