/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Clientes;

import dao.ClientesDAO;
import bean.VmanClientes;
import dao.ClientesDAO;
import tools.Util;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import view.Clientes.JDlgClientes;
import view.Clientes.JDlgClientesPesquisar;

/**
 *
 * @author u10916731103
 */
public class JDlgClientes extends javax.swing.JDialog {

    private JComponent[] CAMPOS_EDICAO;
    private boolean incluir;

    public JDlgClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Usuários");
        setLocationRelativeTo(null);
        Util.habilitar(false, jTxtCodigo, jTxtNome, jBtnCancelar, jBtnConfirmar,
                jCboNivel, jFmtCelular, jCboSEXOOOO,
                jChbAtivo, jFmtCpf, jFmtDataDeNascimento, jPwfSenha, jTxtEmail,
                jCboSEXOOOO, jTxtCidade, jTxtBairro, jTxtendereço,
                jFmtCEP1, jFmtRG, jFmtDivida, jFmtTelefone);

        TitledBorder CPF = BorderFactory.createTitledBorder("CPF");
        TitledBorder DataNasc = BorderFactory.createTitledBorder("Data de Nascimento");
        TitledBorder Cep = BorderFactory.createTitledBorder("CEP");
        TitledBorder Divida = BorderFactory.createTitledBorder("Divida");
        TitledBorder Telefone = BorderFactory.createTitledBorder("Telefone");
        TitledBorder Celular = BorderFactory.createTitledBorder("Celular");
        TitledBorder RG = BorderFactory.createTitledBorder("RG");
        jFmtCpf.setBorder(CPF);
        jFmtCEP1.setBorder(Cep);
        jFmtRG.setBorder(RG);
        jFmtDataDeNascimento.setBorder(DataNasc);
        jFmtTelefone.setBorder(Telefone);
        jFmtCelular.setBorder(Celular);
        jFmtDivida.setBorder(Divida);
        try {
            MaskFormatter maskCpf = new MaskFormatter("###.###.###-##");
            maskCpf.setPlaceholderCharacter('_');
            jFmtCpf.setFormatterFactory(new DefaultFormatterFactory(maskCpf));

            MaskFormatter maskData = new MaskFormatter("##/##/####");
            maskData.setPlaceholderCharacter('_');
            jFmtDataDeNascimento.setFormatterFactory(new DefaultFormatterFactory(maskData));

            // CEP
            MaskFormatter maskCep = new MaskFormatter("#####-###");
            maskCep.setPlaceholderCharacter('_');
            jFmtCEP1.setFormatterFactory(new DefaultFormatterFactory(maskCep));

            // RG
            MaskFormatter maskRg = new MaskFormatter("##.###.###-#");
            maskRg.setPlaceholderCharacter('_');
            jFmtRG.setFormatterFactory(new DefaultFormatterFactory(maskRg));

            MaskFormatter maskTelefone = new MaskFormatter("(##)####-####");
            maskTelefone.setPlaceholderCharacter('_');
            jFmtTelefone.setFormatterFactory(new DefaultFormatterFactory(maskTelefone));

            MaskFormatter maskCelular = new MaskFormatter("(##)#####-####");
            maskCelular.setPlaceholderCharacter('_');
            jFmtCelular.setFormatterFactory(new DefaultFormatterFactory(maskCelular));
        } catch (java.text.ParseException e) {
            e.printStackTrace();
        }

        CAMPOS_EDICAO = new JComponent[]{
            jTxtCodigo, jTxtNome, jBtnCancelar, jBtnConfirmar,
            jCboNivel, jFmtCelular,
            jChbAtivo, jFmtCpf, jFmtDataDeNascimento, jPwfSenha, jTxtEmail,
            jCboSEXOOOO, jTxtCidade, jTxtBairro, jTxtendereço,
            jFmtCEP1, jFmtRG, jFmtDivida, jFmtTelefone
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtCodigo = new javax.swing.JTextField();
        jTxtNome = new javax.swing.JTextField();
        jTxtEmail = new javax.swing.JTextField();
        jFmtCpf = new javax.swing.JFormattedTextField();
        jFmtDataDeNascimento = new javax.swing.JFormattedTextField();
        jPwfSenha = new javax.swing.JPasswordField();
        jChbAtivo = new javax.swing.JCheckBox();
        jCboNivel = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jCboSEXOOOO = new javax.swing.JComboBox<>();
        jFmtDivida = new javax.swing.JFormattedTextField();
        jTxtendereço = new javax.swing.JTextField();
        jTxtBairro = new javax.swing.JTextField();
        jTxtCidade = new javax.swing.JTextField();
        jFmtCEP1 = new javax.swing.JFormattedTextField();
        jFmtTelefone = new javax.swing.JFormattedTextField();
        jFmtRG = new javax.swing.JFormattedTextField();
        jFmtCelular = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTxtCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxtCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Código"));
        jTxtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtCodigoFocusLost(evt);
            }
        });
        jTxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 11, 120, 56));

        jTxtNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxtNome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 96, 100, 60));

        jTxtEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        getContentPane().add(jTxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 96, 153, 60));

        jFmtCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFmtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCpfActionPerformed(evt);
            }
        });
        getContentPane().add(jFmtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 96, 162, 60));
        getContentPane().add(jFmtDataDeNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 97, 219, 60));

        jPwfSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPwfSenha.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha"));
        getContentPane().add(jPwfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 169, 60));

        jChbAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbAtivoActionPerformed(evt);
            }
        });
        getContentPane().add(jChbAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, -1, -1));

        jCboNivel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador", "funcionario", "vendedor", "gerente" }));
        jCboNivel.setBorder(javax.swing.BorderFactory.createTitledBorder("Nivel"));
        jCboNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboNivelActionPerformed(evt);
            }
        });
        getContentPane().add(jCboNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 151, 60));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Ativo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, -1, 21));

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/img/icons8-adicionar-50.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/img/icons8-alterar-50.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/img/icons8-lixo-50.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/img/icons8-confirmar-50.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/img/icons8-cancelar-50.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, -1, -1));

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/img/icons8-pesquisar-50.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, -1, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 268, -1, -1));
        getContentPane().add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(filler3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jCboSEXOOOO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCboSEXOOOO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não-binário", "Gênero fluido", "Agênero", "Bigênero", "Pangênero", "Demiboy", "Demigirl", "Two-Spirit (espiritual/indígena norte-americano)", "Transmasculino", "Transfeminino", "Masculino", "Feminino", "Intersexo", " " }));
        jCboSEXOOOO.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));
        jCboSEXOOOO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboSEXOOOOActionPerformed(evt);
            }
        });
        getContentPane().add(jCboSEXOOOO, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 175, 151, 60));

        jFmtDivida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFmtDivida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtDividaActionPerformed(evt);
            }
        });
        getContentPane().add(jFmtDivida, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 162, 60));

        jTxtendereço.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxtendereço.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));
        getContentPane().add(jTxtendereço, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 175, 140, 60));

        jTxtBairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxtBairro.setBorder(javax.swing.BorderFactory.createTitledBorder("Bairro"));
        getContentPane().add(jTxtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 170, 60));

        jTxtCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxtCidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Cidade"));
        getContentPane().add(jTxtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 140, 60));

        jFmtCEP1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFmtCEP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCEP1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFmtCEP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 173, 162, 60));

        jFmtTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFmtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(jFmtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 162, 60));

        jFmtRG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFmtRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtRGActionPerformed(evt);
            }
        });
        getContentPane().add(jFmtRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 162, 60));

        jFmtCelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFmtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCelularActionPerformed(evt);
            }
        });
        getContentPane().add(jFmtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 162, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:

        Util.habilitar(true, CAMPOS_EDICAO);
        Util.habilitar(false, jBtnAlterar, jBtnExcluir, jBtnIncluir, jBtnPesquisar);
        Util.limpar(jTxtCodigo, jCboNivel, jChbAtivo, jTxtNome, jFmtCpf, jFmtDataDeNascimento, jPwfSenha, jTxtEmail);

        jTxtCodigo.grabFocus();

        incluir = true;
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxtCodigo, jTxtNome, jBtnCancelar, jBtnConfirmar,
                jCboNivel, jChbAtivo, jFmtCpf, jFmtDataDeNascimento, jPwfSenha, jTxtEmail);
        Util.habilitar(false, jBtnAlterar, jBtnExcluir, jBtnIncluir, jBtnPesquisar);

        jTxtNome.grabFocus();

        incluir = false;

    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (Util.perguntar("Deseja realmente excluir o registro?")) {
            Util.mensagem("Registro excluído com sucesso!");
            ClientesDAO clientesDAO = new ClientesDAO();
            try {
                clientesDAO.delete(viewBean());
                Util.limpar(jTxtCodigo, jCboNivel, jChbAtivo, jTxtNome, jFmtCpf, jFmtDataDeNascimento, jPwfSenha, jTxtEmail);
                Util.habilitar(false, jBtnIncluir, jBtnPesquisar);
            } catch (ParseException ex) {
                Logger.getLogger(JDlgClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            Util.mensagem("Exclusão cancelada.");
        }
    }//GEN-LAST:event_jBtnExcluirActionPerformed
    public VmanClientes viewBean() throws ParseException {
        VmanClientes clientes = new VmanClientes();

        clientes.setVmanIdClientes(Util.strToInt(jTxtCodigo.getText()));
        clientes.setVmanNome(jTxtNome.getText());
        clientes.setVmanCpf(jFmtCpf.getText());
        clientes.setVmanRg(jFmtRG.getText());
//      clientes.setVmanSexo((String) jCboSexo.getSelectedItem());
        clientes.setVmanDataNascimento(Util.strToDate(jFmtDataDeNascimento.getText()));
        clientes.setVmanEmail(jTxtEmail.getText());
        clientes.setVmanCep(jFmtCEP1.getText());
        clientes.setVmanendereço(jTxtendereço.getText());
        clientes.setVmanBairro(jTxtBairro.getText());
        clientes.setVmanCidade(jTxtCidade.getText());
        clientes.setVmanTelefoneResidencial(jFmtTelefone.getText());
        clientes.setVmanCelular(jFmtRG.getText());
        clientes.setVmanNivel((String) jCboNivel.getSelectedItem());
        clientes.setVmanDivida(Util.strToInt(jFmtDivida.getText()));

        if (jChbAtivo.isSelected()) {
            clientes.setVmanAtivo("S");
        } else {
            clientes.setVmanAtivo("N");
        }

        return clientes;
    }

    public void beanView(VmanClientes clientes) {
        jTxtCodigo.setText(Util.intToString(clientes.getVmanIdClientes()));
        jTxtNome.setText(clientes.getVmanNome());
        jFmtCpf.setText(clientes.getVmanCpf());
        jCboSEXOOOO.setSelectedItem(clientes.getVmanSexo());
        jFmtDataDeNascimento.setText(Util.dateToStr(clientes.getVmanDataNascimento()));
        jTxtEmail.setText(clientes.getVmanEmail());
        jFmtCEP1.setText(clientes.getVmanCep());
        jTxtendereço.setText(clientes.getVmanendereço());
        jTxtBairro.setText(clientes.getVmanBairro());
        jTxtCidade.setText(clientes.getVmanCidade());
        jFmtTelefone.setText(clientes.getVmanTelefoneResidencial());
        jFmtRG.setText(clientes.getVmanCelular());
        jCboNivel.setSelectedItem(clientes.getVmanNivel());
        jFmtDivida.setText(Util.intToString(clientes.getVmanDivida()));
        jFmtRG.setText(clientes.getVmanRg());

        if ("S".equals(clientes.getVmanAtivo())) {
            jChbAtivo.setSelected(true);
        } else {
            jChbAtivo.setSelected(false);
        }

        // Campos extras
        //jCboSEXOOOO.setSelectedIndex(clientes.getVmanSexo());
    }

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        ClientesDAO clientesDAO = new ClientesDAO();
        if (incluir == true) {
            try {

                clientesDAO.insert(viewBean());

            } catch (ParseException ex) {
                Logger.getLogger(JDlgClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                clientesDAO.update(viewBean());

            } catch (ParseException ex) {
                Logger.getLogger(JDlgClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        Util.limpar(jTxtCodigo, jCboNivel, jChbAtivo, jTxtNome, jFmtCpf, jFmtDataDeNascimento, jPwfSenha, jTxtEmail);

    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here: 
        JDlgClientesPesquisar jDlgClientesPesquisar = new JDlgClientesPesquisar(null, true);
        jDlgClientesPesquisar.setTelaAnterior(this);
        jDlgClientesPesquisar.setVisible(true);
        if (jDlgClientesPesquisar.ok()) {
            Util.habilitar(true, jBtnAlterar, jBtnExcluir);
        }

    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtCodigo, jTxtNome, jBtnCancelar, jBtnConfirmar,
                jCboNivel, jChbAtivo, jFmtCpf, jFmtDataDeNascimento, jPwfSenha, jTxtEmail);
        Util.habilitar(true, jBtnAlterar, jBtnExcluir, jBtnIncluir, jBtnPesquisar);
        Util.limpar(jTxtCodigo, jCboNivel, jChbAtivo, jTxtNome, jFmtCpf, jFmtDataDeNascimento, jPwfSenha, jTxtEmail);


    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTxtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCodigoFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jTxtCodigoFocusLost

    private void jCboNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboNivelActionPerformed

    private void jTxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigoActionPerformed

    private void jFmtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCpfActionPerformed

    private void jCboSEXOOOOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboSEXOOOOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboSEXOOOOActionPerformed

    private void jFmtDividaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtDividaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtDividaActionPerformed

    private void jFmtCEP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCEP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCEP1ActionPerformed

    private void jFmtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtTelefoneActionPerformed

    private void jFmtRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtRGActionPerformed

    private void jChbAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbAtivoActionPerformed

    private void jFmtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCelularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgClientes dialog = new JDlgClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<String> jCboNivel;
    private javax.swing.JComboBox<String> jCboSEXOOOO;
    private javax.swing.JCheckBox jChbAtivo;
    private javax.swing.JFormattedTextField jFmtCEP1;
    private javax.swing.JFormattedTextField jFmtCelular;
    private javax.swing.JFormattedTextField jFmtCpf;
    private javax.swing.JFormattedTextField jFmtDataDeNascimento;
    private javax.swing.JFormattedTextField jFmtDivida;
    private javax.swing.JFormattedTextField jFmtRG;
    private javax.swing.JFormattedTextField jFmtTelefone;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPwfSenha;
    private javax.swing.JTextField jTxtBairro;
    private javax.swing.JTextField jTxtCidade;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtendereço;
    // End of variables declaration//GEN-END:variables
}
